bin/test: Check TypeScript, too

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -4,6 +4,10 @@
 bin/yarn lint &
 eslint_pid=$!
 
+# TypeScript
+bin/yarn tsc &
+tsc_pid=$!
+
 # Slim-Lint
 bundle exec slim-lint . &
 slimlint_pid=$!
@@ -20,6 +24,9 @@ rspec_pid=$!
 wait $eslint_pid
 eslint_exit_code=$?
 
+wait $tsc_pid
+tsc_exit_code=$?
+
 wait $slimlint_pid
 slimlint_exit_code=$?
 
@@ -33,6 +40,11 @@ rspec_exit_code=$?
 if [ $eslint_exit_code -ne 0 ]; then
     echo "ESLint failed"
     exit $eslint_exit_code
+fi
+
+if [ $tsc_exit_code -ne 0 ]; then
+    echo "TypeScript failed"
+    exit $tsc_exit_code
 fi
 
 if [ $slimlint_exit_code -ne 0 ]; then
